package rules.rulesUse;
import unice.polytech.si4.pnsinnov.teamm.drools.FileInfo

rule "mimeTypeFile" salience 3
when
    $file:FileInfo(acceptedMimeType)
then
    $file.moveFile("mimetype");
end

rule "extensionFile" salience 2
when
    $file:FileInfo(acceptedExtensions)
then
    $file.moveFile("extension");
end

rule "default" salience -1000
when
    $file:FileInfo()
then
    $file.moveFile("_NoRuleApplied");
end