package rules;
import unice.polytech.si4.pnsinnov.teamm.drools.FileInfo
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.FileSystems;

rule "Google spreadsheet" salience 5
when
    $file:FileInfo(mimeType == "application/vnd.google-apps.spreadsheet")
then
    System.out.println(" Spreadsheet detected!");
    $file.moveFile("application/vnd.google-apps.spreadsheet");
end

rule "Extension png file" salience 4
when
    $file:FileInfo(extension == "png")
then
    System.out.println("Extension png rule checked !");
    $file.moveFile("PNG");
end

rule "Extension svg file" salience 3
when
    $file:FileInfo(extension == "svg")
then
    System.out.println("Extension svg rule checked !");
    $file.moveFile("SVG");
end

rule "Extension file" salience 2
when
    $file:FileInfo(extension == "pdf")
then
    System.out.println("Extension pdf rule checked !");
    $file.moveFile("PDF");
end

rule "mimeTypeFile" salience 1
when
    $file:FileInfo(mimeType == "application/vnd.google-apps.document")
then
    System.out.println("MIME Type rule checked !");
    $file.moveFile("application/vnd.google-apps.document");
end