package rules;
import unice.polytech.si4.pnsinnov.teamm.drools.FileInfo
import java.nio.file.Files
import unice.polytech.si4.pnsinnov.teamm.drools.FileClassifier
import java.nio.file.Path
import java.nio.file.FileSystems;

rule "mimeTypeFile" salience 3
when
    $file:FileInfo(acceptedMimeType)
then
    $file.moveFile("mimetype");
end

rule "extensionFile" salience 2
when
    $file:FileInfo(acceptedExtensions)
then
    $file.moveFile("extension");
end

rule "default" salience -1000
when
    $file:FileInfo()
then
    $file.moveFile("_NoRuleApplied");
end